$(document).ready(function(){getPrice($("#optioni").val());$(".variationSelect select").change(function(){getPrice($("#optioni").val());});$("[rel='addBasket']").click(function(){addtobasket();});});function showNoZoom(){$(".noZoomAvailable").show();}
function showreviews(){$("ul.tabs").data("tabs").click(2);}
function addtobasket(){$.ajax({cache:false,async:true,type:'POST',url:'app/ajax/wte.php',data:$('#aB').serialize(),success:function(data){console.log(data);site__basket_add(data);}});}
function IsJsonString(str){try{jQuery.parseJSON(str);}catch(e){return false;}
return true;}
function reloadOption(){}
function add_vial_load(){$(".vial_size img").removeClass("hidden");$(".vial_size img").addClass("faded");$(".variation_guide").removeClass("hidden");$(".variation_guide").addClass("hidden");}
function remove_vial_load(){$(".vial_size img").removeClass("hidden");$(".vial_size img").removeClass("faded");$(".variation_guide").removeClass("hidden");$(".variation_guide").removeClass("faded");}
function hide_vial_load(){$(".variation_guide").addClass("hidden");$(".vial_size img").addClass("hidden");}
function change_variation_guide(text){console.log(text);setTimeout(function(){$(".variation_guide").html(text);},1000);}
function change_vial_photo(which){console.log(which);setTimeout(function(){$(".vial_size img").attr("src","interface/assets/images/bottles/"+which+".png");remove_vial_load();},1000);}
function getPrice(productID){var variations=new Array();var selected=new Array();$(".variationSelect").each(function(index){var id=$(this).attr("id");id=id.replace('vt','');variations[index]=id;selected[index]=$("#"+$(this).attr("id")+" select").val();});$.ajax({type:"POST",cache:false,url:'app/ajax/api.connect.seamless.php',data:{a:'getPrice',i:productID,array:selected},error:function(data){}}).done(function(data){console.log(data);if(IsJsonString(data)){var obj=jQuery.parseJSON(data);if(obj.variation_image!==""){console.log(decodeURIComponent(obj.variation_image));$(".variable_seamless_image img").attr("src",decodeURIComponent(obj.variation_image));$("#Seamless_image_changed").val(1);}else{if($("#Seamless_image_changed").val()===1){$("#Seamless_image_changed").val(0);$(".variable_seamless_image img").attr("src",$("#Seamless_original_image").val());}}
if(obj.giftbox==='yes'){$(".gift_box_data").html(obj.gift_box_content);}
if(obj.nosell==='1'){$("#PRODREF").hide();$("#STOCKSTATUS").show();$("#STOCKSTATUS").html('Variation not for sale');$("input[rel=addBasket]").attr("disabled","disabled");$("#optionv").val('');$("#var__vat_sel").html('');$("#var__vat_sel").hide();$("#var__price_sel").html('');$("#var__sale_sel").html('');$("#var__rrp_sel").html('');$("#PRICE").show();$("#SAVE, #RRP").hide();}else{$("input[rel=addBasket]").removeAttr("disabled");$("#optionv").val(obj.id);if(obj.reference!==''){$("#PRODREF").show();$("#PRODREF").html(obj.reference);}else{$("#PRODREF").hide();}
add_vial_load();var matched=false;var str=obj.varTitle;if(str.indexOf("1ml")!==-1){change_vial_photo("1");change_variation_guide("Will last you 3-4 wearings");matched=true;}else if(str.indexOf("2ml")!==-1){change_vial_photo("2");change_variation_guide("Will last you 7-8 wearings");matched=true;}else if(str.indexOf("3ml")!==-1){change_variation_guide("");change_vial_photo("3");matched=true;}else if(str.indexOf("5ml")!==-1){change_variation_guide("Will last you 2 weeks of wearing");change_vial_photo("5");matched=true;}else if(str.indexOf("10ml")!==-1){change_variation_guide("Will last you 1 month of wearing");change_vial_photo("10");matched=true;}else if(str.indexOf("20ml")!==-1){change_variation_guide("Will last you 2 months of wearing");change_vial_photo("20");matched=true;}else if(str.indexOf("30ml")!==-1){change_vial_photo("30");change_variation_guide("Will last you 3 months of wearing");matched=true;}else if(str.indexOf("50ml")!==-1){change_vial_photo("50");change_variation_guide("Will last you 5 months of wearing");matched=true;}
if(!matched){hide_vial_load();}
console.log(obj.varTitle);if(obj.varTitle!==''){$("#VARTITLE").show();$("#VARTITLE").html(''+obj.varTitle);}else{$("#VARTITLE").hide();}
if(obj.instock===0){$("#outofstockmessage").show();$(".addButton").hide();}else{$("#outofstockmessage").hide();$(".addButton").show();}
if(obj.stockMessage===''){$("#STOCKSTATUS").hide();$("#STOCKSTATUS").html('');}else{$("#STOCKSTATUS").show();$("#STOCKSTATUS").html(obj.stockMessage);}
if(obj.vatMessage===''){$("#var__vat_sel").html('');$("#var__vat_sel").hide();}else{$("#var__vat_sel").html(obj.vatMessage);$("#var__vat_sel").show();}
if(obj.offer==='1'){$("#var__price_sel").html('&pound;'+obj.saleprice);$("#var__sale_sel").html('&pound;'+obj.save);$("#var__rrp_sel").html('&pound;'+obj.price);$("#SAVE, #RRP, #PRICE").show();}else{$("#var__price_sel").html('&pound;'+obj.price);$("#var__sale_sel").html('');$("#var__rrp_sel").html('');$("#PRICE").show();$("#SAVE, #RRP").hide();}}}});}